import React, { useState, useEffect } from 'react';
import { supabase } from '../../lib/supabase';
import { ClipboardList, Plus, Search, Filter, X, Calendar, AlertCircle, Loader2 } from 'lucide-react';

export default function Assignments() {
  const [assignments, setAssignments] = useState([]);
  const [sessions, setSessions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showModal, setShowModal] = useState(false);
  const [dbError, setDbError] = useState(false);
  
  // Form State
  const [formData, setFormData] = useState({
    title: '',
    description: '',
    due_date: '',
    max_points: 100,
    session_id: ''
  });
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    setLoading(true);
    setDbError(false);
    try {
      // 1. Fetch Assignments
      const { data: assignmentsData, error: assignmentsError } = await supabase
        .from('assignments')
        .select(`
          *,
          sessions (
            topic,
            date
          )
        `)
        .order('created_at', { ascending: false });

      if (assignmentsError) {
        if (assignmentsError.code === 'PGRST116' || assignmentsError.message.includes('does not exist')) {
          setDbError(true);
        } else {
          throw assignmentsError;
        }
      } else {
        setAssignments(assignmentsData || []);
      }

      // 2. Fetch Sessions for the dropdown
      const { data: sessionsData, error: sessionsError } = await supabase
        .from('sessions')
        .select('id, topic, date')
        .order('date', { ascending: false });

      if (sessionsError) throw sessionsError;
      setSessions(sessionsData || []);

    } catch (err) {
      console.error('Error fetching data:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleCreate = async (e) => {
    e.preventDefault();
    
    // Date Validation: Check if due date is in the past
    const selectedDate = new Date(formData.due_date);
    const today = new Date();
    today.setHours(0, 0, 0, 0); // Reset time for comparison
    
    if (selectedDate < today) {
      alert('The due date has already passed. Please select a future date.');
      return;
    }

    setSubmitting(true);
    try {
      const { error } = await supabase
        .from('assignments')
        .insert([{
          ...formData,
          session_id: formData.session_id || null,
          due_date: selectedDate.toISOString()
        }]);

      if (error) throw error;

      setShowModal(false);
      setFormData({ title: '', description: '', due_date: '', max_points: 100, session_id: '' });
      fetchData();
    } catch (err) {
      console.error('Error creating assignment:', err);
      alert('Failed to create assignment. Please make sure the assignments table exists in your database.');
    } finally {
      setSubmitting(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-accent-glow"></div>
      </div>
    );
  }

  return (
    <div className="max-w-7xl mx-auto p-6 space-y-8">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div className="space-y-2">
          <div className="flex items-center gap-2 text-accent-glow">
            <ClipboardList size={20} />
            <span className="text-sm font-semibold tracking-wider uppercase">Activities</span>
          </div>
          <h2 className="text-display-sm text-primary">Assignments</h2>
          <p className="text-body text-secondary">Manage and track student assignments and submissions.</p>
        </div>

        <button 
          onClick={() => setShowModal(true)}
          className="btn-primary"
        >
          <Plus size={18} className="mr-2" />
          Create Assignment
        </button>
      </div>

      {dbError ? (
        <div className="card border-rose-500/20 bg-rose-500/5 p-8 text-center space-y-4">
          <div className="w-16 h-16 rounded-2xl bg-rose-500/10 flex items-center justify-center text-rose-500 mx-auto">
            <AlertCircle size={32} />
          </div>
          <div className="space-y-2">
            <h3 className="text-xl font-bold text-primary">Database Setup Required</h3>
            <p className="text-secondary max-w-lg mx-auto">
              The assignments table was not found in your Supabase database. Please run the SQL migration to enable this feature.
            </p>
            <div className="bg-surface-inset p-4 rounded-lg text-left overflow-x-auto max-w-2xl mx-auto border border-subtle">
              <pre className="text-xs text-tertiary font-mono">
{`CREATE TABLE public.assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  due_date TIMESTAMP WITH TIME ZONE NOT NULL,
  max_points INTEGER DEFAULT 100,
  session_id BIGINT REFERENCES public.sessions(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
  status TEXT DEFAULT 'active'
);`}
              </pre>
            </div>
          </div>
        </div>
      ) : assignments.length === 0 ? (
        <div className="card border-subtle bg-surface-raised p-12 text-center space-y-4">
          <div className="w-16 h-16 rounded-2xl bg-accent-glow/10 flex items-center justify-center text-accent-glow mx-auto">
            <ClipboardList size={32} />
          </div>
          <div className="space-y-2">
            <h3 className="text-xl font-bold text-primary">No Assignments Yet</h3>
            <p className="text-secondary max-w-md mx-auto">
              Start by creating your first assignment to track student progress and collect submissions.
            </p>
          </div>
          <button 
            onClick={() => setShowModal(true)}
            className="btn-secondary mt-4"
          >
            Create Your First Assignment
          </button>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {assignments.map((assignment) => (
            <div key={assignment.id} className="card border-subtle hover:border-accent-glow transition-all group p-6 space-y-4 flex flex-col">
              <div className="flex justify-between items-start">
                <span className="px-2 py-0.5 rounded-md bg-accent-glow/10 text-accent-glow text-[10px] font-bold uppercase tracking-wider">
                  {assignment.status}
                </span>
                <span className="text-xs text-tertiary flex items-center">
                  <Calendar size={12} className="mr-1" />
                  Due: {new Date(assignment.due_date).toLocaleDateString()}
                </span>
              </div>
              
              <div className="flex-1">
                <h3 className="text-lg font-bold text-primary group-hover:text-accent-glow transition-colors">
                  {assignment.title}
                </h3>
                <p className="text-sm text-secondary line-clamp-2 mt-1">
                  {assignment.description || 'No description provided.'}
                </p>
              </div>

              {assignment.sessions && (
                <div className="py-2 px-3 bg-surface-inset rounded-lg border border-subtle">
                  <p className="text-[10px] text-tertiary uppercase font-bold tracking-widest mb-1">Linked Session</p>
                  <p className="text-xs text-secondary truncate">{assignment.sessions.topic}</p>
                </div>
              )}

              <div className="pt-4 border-t border-subtle flex items-center justify-between">
                <div className="flex flex-col">
                  <span className="text-xs text-tertiary uppercase font-bold tracking-tighter">Max Points</span>
                  <span className="text-sm font-bold text-primary">{assignment.max_points}</span>
                </div>
                <button className="btn-secondary py-1.5 px-4 text-xs h-auto">
                  View Submissions
                </button>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Creation Modal */}
      {showModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          <div className="absolute inset-0 bg-void/80 backdrop-blur-sm" onClick={() => setShowModal(false)} />
          <div className="relative bg-surface-raised border border-strong rounded-2xl w-full max-w-lg shadow-2xl overflow-hidden animate-in fade-in zoom-in duration-200">
            <div className="p-6 border-b border-subtle flex justify-between items-center">
              <h3 className="text-xl font-bold text-primary">New Assignment</h3>
              <button onClick={() => setShowModal(false)} className="p-2 hover:bg-surface-inset rounded-lg transition-colors">
                <X size={20} />
              </button>
            </div>
            
            <form onSubmit={handleCreate} className="p-6 space-y-5">
              <div className="space-y-2">
                <label className="text-xs font-bold text-tertiary uppercase tracking-widest">Title</label>
                <input 
                  required
                  type="text" 
                  placeholder="e.g., Python Basics Quiz"
                  className="input w-full"
                  value={formData.title}
                  onChange={(e) => setFormData({...formData, title: e.target.value})}
                />
              </div>

              <div className="space-y-2">
                <label className="text-xs font-bold text-tertiary uppercase tracking-widest">Description</label>
                <textarea 
                  rows={3}
                  placeholder="What needs to be done?"
                  className="input w-full resize-none py-3"
                  value={formData.description}
                  onChange={(e) => setFormData({...formData, description: e.target.value})}
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="text-label text-tertiary block mb-2 uppercase">Due Date</label>
                <input
                  type="date"
                  className="input cursor-pointer"
                  value={formData.due_date}
                  onClick={(e) => e.target.showPicker?.()}
                  onChange={(e) => setFormData({ ...formData, due_date: e.target.value })}
                  required
                />
              </div>
              <div>
                <label className="text-label text-tertiary block mb-2 uppercase">Max Points</label>
                <input
                  type="number"
                  className="input"
                  placeholder="Points (e.g. 100)"
                  value={formData.max_points === 0 ? '' : formData.max_points}
                  onChange={(e) => {
                    const val = e.target.value;
                    setFormData({ ...formData, max_points: val === '' ? '' : parseInt(val) });
                  }}
                  required
                />
              </div>
            </div>

              <div className="space-y-2">
                <label className="text-xs font-bold text-tertiary uppercase tracking-widest">Linked Session (Optional)</label>
                <select 
                  className="input w-full"
                  value={formData.session_id}
                  onChange={(e) => setFormData({...formData, session_id: e.target.value})}
                >
                  <option value="">No Session Link</option>
                  {sessions.map(s => (
                    <option key={s.id} value={s.id}>
                      {new Date(s.date).toLocaleDateString()} - {s.topic}
                    </option>
                  ))}
                </select>
              </div>

              <div className="flex gap-3 pt-4">
                <button 
                  type="button"
                  onClick={() => setShowModal(false)}
                  className="btn-secondary flex-1"
                >
                  Cancel
                </button>
                <button 
                  type="submit"
                  disabled={submitting}
                  className="btn-primary flex-1 flex items-center justify-center gap-2"
                >
                  {submitting ? (
                    <>
                      <Loader2 size={18} className="animate-spin" />
                      Creating...
                    </>
                  ) : 'Create Assignment'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
